version: '3.8'

services:
    laravel-app:
        build:
            context: .
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        command: >
            sh -c "composer install &&
                   php artisan key:generate &&
                   php artisan serve --host=0.0.0.0 --port=8000"

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: Manorashed@11
            MYSQL_DATABASE: shipping
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravelpass
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
